apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-argo-application
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/k4shE/argocd-config.git
      targetRevision: HEAD
      path: dev
    - repoURL: https://github.com/k4shE/vault-app.git
      targetRevision: HEAD
      path: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true